name: Build with Nuitka

on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger on changes to .py files in root directory
  push:
    paths:
      - '*.py'
    branches: [ main ]
  
  pull_request:
    paths:
      - '*.py'
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'arm64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install pandas requests openpyxl
    
    - name: Build with Nuitka
      run: |
        python -m nuitka --onefile --output-filename=XTF XTF.py
    
    - name: Create artifact directory
      run: |
        mkdir -p artifacts
    
    - name: Copy files to artifacts
      run: |
        cp XTF artifacts/
        cp config.example.json artifacts/
        chmod +x artifacts/XTF
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: XTF-macos-arm64-nuitka
        path: artifacts/
        retention-days: 30

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install pandas requests openpyxl
    
    - name: Build with Nuitka
      run: |
        python -m nuitka --onefile --output-filename=XTF.exe XTF.py
    
    - name: Create artifact directory
      run: |
        mkdir artifacts
    
    - name: Copy files to artifacts
      run: |
        copy XTF.exe artifacts\
        copy config.example.json artifacts\
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: XTF-windows-x64-nuitka
        path: artifacts/
        retention-days: 30